export { default as Add } from "./add";
export { default as Path } from "./Path";
export { default as Paths } from "./Paths";
export { default as Home } from "./home";
export { default as Login } from "./login";
export { default as Message } from "./message";
export { default as Messages } from "./messages";
export { default as MyPaths } from "./MyPaths";
export { default as Orders } from "./orders";
export { default as Register } from "./register";
export { default as Learn } from "./Learn"
