export { default as Navbar } from "./navbar";
export { default as Featured } from "./featured";
export { default as TrustedBy } from "./trustedBy";
export { default as CatCard } from "./catCard";
export { default as Footer } from "./footer";
export { default as PathCard } from "./pathCard";
export { default as ProjectCard } from "./projectCard";
export { default as Slide } from "./slide";
export { default as Loader } from "./loader";
export { default as Spinner } from "./Spinner"
export { default as SubCard } from "./subCard"
export { default as MateriCard } from "./materiCard"
export { default as ActiveMateriCard } from "./ActiveMateriCard"
export { default as LearnVideoCard } from "./LearnVideoCard"
export { default as RegisClass } from "./regisClass"
export { default as ReviewSec } from "./ReviewSec"